name: bonfry_wallet
description: App per segnare le tue transazioni

version: 1.2.0+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.0.0+3
  path: ^1.8.0
  intl: ^0.17.0
  flutter_colorpicker: ^0.4.0
  package_info: ^2.0.0
  url_launcher: ^6.0.2
  path_provider: ^2.0.1
  permission_handler: "^6.1.1"
  shared_preferences: ^2.0.5
  google_fonts: ^2.0.0
  flutter_icons: ^1.1.0
  equatable: ^2.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
