name: bonfry_wallet
description: App per segnare le tue transazioni

version: 1.2.0+8

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  sqflite: ^1.2.1
  path: ^1.6.4
  intl: ^0.16.1
  flutter_colorpicker: ^0.3.2
  package_info: 0.4.0+14
  url_launcher: ^5.4.2
  folder_picker: ^0.3.0
  file_picker: ^1.4.3+2
  path_provider: ^1.6.1
  permission_handler: '^4.2.0+hotfix.3'
  shared_preferences: ^0.5.6+2
  google_fonts: ^0.3.9
  flutter_icons: ^1.0.0+1
  sqfentity: ^1.2.2+8
  sqfentity_gen: ^1.2.0+13

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.6.5
  build_verify: ^1.1.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/BWallet.png
    - images/splash_logo.png
    - images/splash_name_logo.png
    - images/home_icon.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
